export default function Home() {
  return (
    <div className="imgCollection-container">
      <div className="imgCollection">
        <div className="row small">
          <div className="imagegroup" style={{ animationDelay: "1s" }}>
            <img
              src={require("../images/cake1.jpg")}
              alt="cake1"
              className="img-top"
            />
            <img
              src={require("../images/cake2.jpeg")}
              alt="cake1"
              className="img-top"
            />
            <img
              src={require("../images/cake3.jpeg")}
              alt="cake1"
              className="img-top"
            />
            <img
              src={require("../images/cake4.jpeg")}
              alt="cake1"
              className="img-top"
            />
            <img
              src={require("../images/cake5.jpeg")}
              alt="cake1"
              className="img-top"
            />
            <img
              src={require("../images/cake1.jpg")}
              alt="cake1"
              className="img-top"
            />
            <img
              src={require("../images/cake3.jpeg")}
              alt="cake1"
              className="img-top"
            />
            <img
              src={require("../images/cake4.jpeg")}
              alt="cake1"
              className="img-top"
            />
            <img
              src={require("../images/cake5.jpeg")}
              alt="cake1"
              className="img-top"
            />
            <img
              src={require("../images/cake1.jpg")}
              alt="cake1"
              className="img-top"
            />
          </div>
        </div>
        <div className="row large">
          <div className="imagegroup" style={{ border: "2px solid white" }}>
            <img
              src={require("../images/cake3.jpeg")}
              alt="cake1"
              className="img-middle"
            />
            <img
              src={require("../images/cake4.jpeg")}
              alt="cake1"
              className="img-middle"
            />
            <img
              src={require("../images/cake3.jpeg")}
              alt="cake1"
              className="img-middle"
            />
            <img
              src={require("../images/cake4.jpeg")}
              alt="cake1"
              className="img-middle"
            />
          </div>
        </div>
        <div className="row small">
          <div className="imagegroup" style={{ animationDelay: "1s" }}>
            <img
              src={require("../images/cake1.jpg")}
              alt="cake1"
              className="img-bottom"
            />
            <img
              src={require("../images/cake2.jpeg")}
              alt="cake1"
              className="img-bottom"
            />
            <img
              src={require("../images/cake3.jpeg")}
              alt="cake1"
              className="img-bottom"
            />
            <img
              src={require("../images/cake4.jpeg")}
              alt="cake1"
              className="img-bottom"
            />
            <img
              src={require("../images/cake5.jpeg")}
              alt="cake1"
              className="img-bottom"
            />
            <img
              src={require("../images/cake1.jpg")}
              alt="cake1"
              className="img-bottom"
            />
            <img
              src={require("../images/cake3.jpeg")}
              alt="cake1"
              className="img-bottom"
            />
            <img
              src={require("../images/cake4.jpeg")}
              alt="cake1"
              className="img-bottom"
            />
            <img
              src={require("../images/cake5.jpeg")}
              alt="cake1"
              className="img-bottom"
            />
            <img
              src={require("../images/cake1.jpg")}
              alt="cake1"
              className="img-bottom"
            />
          </div>
        </div>
      </div>
    </div>
  );
}
